services:
  - type: web
    name: rakshasutra
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8080
