services:
  - type: web
    name: rakshasutra
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@rakshasutra.org
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./rakshasutra.db
